### ISSUE TITLE
getting inspiration from cycle-onionify

### ISSUE THREAD

**Issue by obedm503** [zewa666/aurelia-store#12]
https://github.com/staltz/cycle-onionify

given that both aurelia-store and cycle-onionify dispatch functions instead of objects like redux, it may be worth while to get api inspiration from onionify. 

something else that may be related: why does aurelia-store require the registration of the action functions?

**Comment by zewa666** [comment]
Certainly, i've recently taken a look at onionify and it Looks quite nice and ties very well into rxjs and all streamed based development. The idea of Aurelia Store is to use rxjs merely for the BehaviorSubject, so Users do not have to understand anything besides subscribing to the public observable. But of course for the ones enjoying Rxjs there are tons of more great opportunities. I'd like to maintain both approaches.

Which parts of onionify so you think would be specifically worth looking at?

Regarding registration, there is no immediately effective reason. It could in future though introduce benefits knowing all available actions in advance. This could very well though be dropped as well If we don't see any need for it with upcoming features.

**Comment by obedm503** [comment]
>Which parts of onionify so you think would be specifically worth looking at?
nothing in specific, it just really caught my attention the whole dispatch functions instead of objects

**Comment by zewa666** [comment]
The thing that scares me a bit is the fractal state approach as it really forces you all the way down into casading stream compositions, which frankly would be an overkill for most existing Apps. One of the hardest challenges, given the relatively OOP direction of most Aurelia parts, will be to sprinkle just *enough* functional approaches as a min yet maintain flexibility for all styles. Lets see how tha works out 😜
