### ISSUE TITLE
How to use state history when modifying arrays.

### ISSUE THREAD

**Issue by 4imble** [zewa666/aurelia-store#13]
I am having a go at swapping out my old implementation to use aurelia-store. My current implementation is is essentially a copy of what you did here: https://github.com/zewa666/aurelia-hoc-store

I am interested in having the state history work from the beginning but can't quite get my head round it.

I would find it super helpful if you could show how the same code above would work (including undo) if one was using aurelia-store instead.

Just a suggestion, if I can't get it right i'll just carry on with using the pattern you prescribed in the post (which may be better for me as newbie to get the concepts down anyway).

Happy to talk outside of here if it helps. 
Many thanks, 4imble

**Comment by zewa666** [comment]
Sure I'll recreate the sample over at the aurelia-store-examples repo.

**Comment by 4imble** [comment]
Wicked, thanks!

**Comment by zewa666** [comment]
Ok so I've added the example as it is right now. It does not include history support yet. So I'd like to ask you to try out how it would work to add that, that way you could check out whether the documentation and other history examples are sufficient enough to guide you how to do that.

**Comment by 4imble** [comment]
Sorry, where have you added it - here: https://github.com/zewa666/aurelia-store-examples ?

**Comment by zewa666** [comment]
Yep its in the services folder

**Comment by zewa666** [comment]
@4imble did you manage to get the history support in?

**Comment by 4imble** [comment]
@zewa666 Sorry, I am using this in a personal project and not had chance to give it a go properly yet. I stay behind late after work on Tuesdays to work on my own stuff, so have been looking forward to trying it out then. Will let you know how it goes! 👍

**Comment by zewa666** [comment]
No trouble just wanted to see what's happening and whether you got stuck with something

**Comment by zewa666** [comment]
Closing this for now
