### ISSUE TITLE
Make the localStorage aurelia-store-state name configurable

### ISSUE THREAD

**Issue by ben-girardet** [zewa666/aurelia-store#14]
https://github.com/zewa666/aurelia-store/blob/5557360c76fb93e8ba5522cd2ac7728583822e36/src/middleware.ts#L13

Would be nice to be able to change the name of the localStorage variable when configuring the plugin.

**Comment by zewa666** [comment]
Ok it seems there are more and more reasons to provide configs for middlewares. Will think of a better API to allow that

**Comment by zewa666** [comment]
Its implemented now with the addition of middleware settings parameters. Just pass in a third parameter being an object with a property `key` and as value the string to be used
