### ISSUE TITLE
Provide action.name and params to middleware

### ISSUE THREAD

**Issue by kennyfowler** [zewa666/aurelia-store#17]
I'm trying to explain this with an example.

I dont know if my pattern is flawed, but with redux it was kind of easy to implement some kind of "actions-lock":
* i had an additional reducer that listened to certain actions, i then applied data to the state that holds info which future actions will be allowed to execute, and which actions will remove the lock.
* in middleware i had access to the dispatched action (name and params) and could check if it's allowed to execute and/or to remove the lock (refuse execution and/or remove the data from the state)

I think i could do something similar by wrapping the store or monkeypatching the dispatch function, but maybe there are other cases where this might be handy if its implemented in aurelia-store

**Comment by zewa666** [comment]
This definitely sounds useful. Few questions:

1. By provide params you mean the parameters provided to the action should be accessible inside the middleware?
2. The lock behavior is specific to your app or was that also a side-feature-request? Sounds more like your personal way to achieve things right?

Monkeypatching should clearly be the last resort so it would be awesome if you could sketch a use-case of what you're trying to achieve. This pretty much sounds like it goes into the direction of *conditional* middlewares, based on the action dispatched, but I'd like to really understand the use-case you're trying to achieve here, so maybe in a few words or a chart if it helps, try to summarize what your app would be doing.

**Comment by kennyfowler** [comment]
> 1. By provide params you mean the parameters provided to the action should be accessible inside the middleware?

Yes. In redux i dispatch an object which contains the action-name and any data i provide, this object is passed to middleware. If i map this to aurelia-store, this would be the action-name and the params provided to the action

> 2. The lock behavior is specific to your app or was that also a side-feature-request? Sounds more like your personal way to achieve things right?

The lock behavior was just an example why this feature (action data accessible in middleware) was helpful in redux, it hast nothing to do with the suggestion.

Example explained (not the feature request):

Lets say i can view a parent entity with all of its sub-items. I have edit-buttons for the parent and for each sub-item. If i click one of the edit-buttons, the view of the parent OR one of the sub-items switches to a form. In this state, i dont want to happen anything else than save or cancel. How can i pevent from clicking another edit-button or executing another action (other than save and cancel)? Because all changes are strictly done by actions, i simply could prevent executing other actions than save and cancel. if another action is dispatched, i refuse to execute it (possible in redux) and post a notification (toaster). I did this check in middleware. This seemed to be much more straight forward than implement code to disable or hide buttons in the ui, or checking on every click-handler before dispatching.

To do this i needed to know in middleware which action is currently executed.

**Comment by zewa666** [comment]
But shouldnt the conditional whether allowed or not be part of the edit action itself? State would perhaps have an editedId and If that is not null then simply return the same state thus no modification. But i can see the need to put all conditional logic together in one middleware.

**Comment by kennyfowler** [comment]
> But shouldnt the conditional whether allowed or not be part of the edit action itself? State would perhaps have an editedId and If that is not null then simply return the same state thus no modification.

Well, if i have some other buttons on the page that trigger other actions, eg. "logout", i would have to check on every button if an editId is set, instead i put the check into middleware which can check the state, and return the original state if not allowed, _yes, thought about that, would work._

But... if the save- or cancel-action is getting dispatched, the editId is still set, so even these actions would return the original state.... thats the point where i needed to know the action-name

maybe the comparison to to the request-pipeline is valid, i can implement filters that can alter the request before it hits the controller, in some cases the filter revokes the request because a cookie is missing... but the filter / middleware needs to know about the request / action.

**Comment by zewa666** [comment]
Overall i think the example as described is great. I'll create something like that for the examples repo, since i need anyway something to show off the connectTo decorator and will try to get a logic for that case worked out. I'll ping you with a link to the branch so we can continue the discussion based on that sample.

**Comment by kennyfowler** [comment]
Just logging an idea that came up in the office today, a little bit ugly, but would fullfill my needs:

I could save the action-name or any other data through the action itself to the state, i then could read that data (action-name) in middleware (after) and alter the state to my needs, or just return the original state.

But i would still need to implement that (saving current action-name to state) in every action.

**Comment by zewa666** [comment]
damn i'm buried under tons of tasks in my day job, so I'm not sure I'll gonna make it this week with the example. If you wanna start with the sample by yourself @kennyfowler that would greatly help. Otherwise I hope I can get to it next week

**Comment by kennyfowler** [comment]
I will setup a repo and send it on the weekend, you can then review if it would add value to your examples...

**Comment by kennyfowler** [comment]
@zewa666 please feel free to review, comment, use or ignore the example (which would be better to achieve if the middleware would receive the action name). if this example may be helpful, i'm open to further improve the example to your needs...

https://github.com/kennyfowler/aurelia-store-action-middleware-example

**Comment by zewa666** [comment]
Thanks Ill review as soon as possible

**Comment by zewa666** [comment]
Alright I've gone through the sample and let me first say it's really great. Looking forward to get this merged once we have the new API in place. It's really a super cool, often used case.

So as I see, this request actually includes two requests.
First, you'd need the actions name and params passed in which would be a for this

```typescript
export interface CallingAction {
  name: string;
  params?: any[];
}

export type Middleware<T> = (state: T, originalState?: T, settings?: any, action?: CallingAction) => T | Promise<T | undefined> | void;
```

Second, you'd need a way to stop the further processing, thus not `next`ing the next state in case a middleware returns `false`.

Is that right?

**Comment by zewa666** [comment]
So I've added the new branch, which you can check out I think by installing

```bash
npm install git://github.com/zewa666/aurelia-store.git#middleware-action --save
```

This includes the first part mentioned in above reply. Looking forward to see whether this helps you.

**Comment by kennyfowler** [comment]
@zewa666 thx, will comment asap

**Comment by zewa666** [comment]
hey @kennyfowler, did you have a chance to look at the changes?

**Comment by kennyfowler** [comment]
@zewa666 sorry for the late reply. changes work as expected. updated my example repo. i saw you also worked on revoking the action... will also update to that change when its ready.

https://github.com/kennyfowler/aurelia-store-action-middleware-example

**Comment by zewa666** [comment]
@kennyfowler cool thanks for the feedback. I'll try to get the other feature finished so that you can update the example even further and avoid unnecessary new state creations.

**Comment by zewa666** [comment]
New release is out with this feature included
