### ISSUE TITLE
Aurelia Store does not work with server-side rendering

### ISSUE THREAD

**Issue by Vheissu** [zewa666/aurelia-store#18]
When Aurelia is being used in a server-side rendering context, window and other variables do not exist. This line [here](https://github.com/zewa666/aurelia-store/blob/493cede4c096a7f1f667c73a28dafd09831e1b62/src/store.ts#L207) checks for dev tools. The fix I believe is to not directly use `window` and rather use something like `PLATFORM.global` instead. I may submit a PR for this when I find the time.

**Comment by zewa666** [comment]
Good catch thanks will go over that. Would be great to have a simple SSR example in the samples repo wired up with the Store plugin

**Comment by zewa666** [comment]
Fixed that with the new release 0.19.1
