### ISSUE TITLE
A few more browser specific calls are breaking plugin with server-side rendering

### ISSUE THREAD

**Issue by Vheissu** [zewa666/aurelia-store#19]
Sorry, I found another browser API being used breaking server-side rendering, the `performance` API appears to be used extensively for recording performance metrics. Looks like all calls to `performance.` will need to be replaced with the Aurelia PAL equivalent.

**Comment by zewa666** [comment]
@Vheissu thanks for the hint, as soon as all pals are released I'll be adding a fix for this one

**Comment by Vheissu** [comment]
Love your work @zewa666

**Comment by zewa666** [comment]
@Vheissu the latest release 0.19.2 now contains the update pal and fixes for the platform.performance abstraction. Please give it a test run for your SSR implementation

**Comment by Vheissu** [comment]
Fixed. Perfect.
