### ISSUE TITLE
decorator naming

### ISSUE THREAD

**Issue by bigopon** [zewa666/aurelia-store#24]
`@connectTo` vs `@autoconnect` ?

With `@autoconnect`, I think we have a better excuse to look for property `state` than `@connectTo`

**Comment by zewa666** [comment]
Hmm but reading this line:
```typescript
@connectTo<State>((store) => store.state.pluck("bar"))
```

wouldn't you spell it as: *Connect to the result of lambda* ?

Alternatively what if we just create an alias?

**Comment by bigopon** [comment]
I was only thinking about the usage on class, `autoconnect` still doesn't sound good on that line. Maybe keep it as is 👍

**Comment by zewa666** [comment]
Closing for know, lets reopen if we have any better idea
