### ISSUE TITLE
Dispatch by name?

### ISSUE THREAD

**Issue by khuongduybui** [zewa666/aurelia-store#26]
Why do I need to dispatch actions by function handlers instead of just the names I registered these functions with?

Right now I need to inject my services (where my action functions live) into my views to dispatch these actions. Ideally, I don't want to have to inject anything and instead simply import connectTo and dispatchify.

**Comment by zewa666** [comment]
Very good argument and I have actually no answer on why I didnt think about that. Makes definitely a nice feature

**Comment by zewa666** [comment]
alright I've added the feature and released a new version. If you @khuongduybui could give it a try, that would be very helpful. It should accept the registered name as string, both in `dispatch` but also `dispatchify`

**Comment by khuongduybui** [comment]
Thanks for the quick turnaround. I'll definitely check it out this weekend.

**Comment by khuongduybui** [comment]
I tested both `dispatch` and `dispatchify`. Seems to work as expected.
