### ISSUE TITLE
dispatchify to return the promise from dispatch

### ISSUE THREAD

**Issue by MatthewSwarbrick** [zewa666/aurelia-store#27]
I'm currently writing tests to check actions are called and the state gets updated properly. In my assertion steps I need to wait for the state to be changed once the actions have been raised. I was using the dispatchify function to reduce dependencies in my view models, but dispatchify doesn't return a promise so am unable to use async/await. And thus can't gaurantee the state has been updated at the point of my assertion steps.

I can work around this, by calling dispatch directly on store and using async/await. 

I am unable to do this with dispatchify. It seems simple enough to return the promise on the dispatchify function?

Thanks for your time

**Comment by zewa666** [comment]
You're right that was just an oversight, will add this with the next release

**Comment by zewa666** [comment]
@MatthewSwarbrick should be fixed with the latest patch release

**Comment by zewa666** [comment]
Closing this for know. If you still experience any issues we can reopen it
