### ISSUE TITLE
Allow connectTo to return a different type and the same as the input

### ISSUE THREAD

**Issue by Belpois** [zewa666/aurelia-store#29]
The example below exposes `T` but returns what is selected by the map which is `R`

```ts
@connectTo<T, R>({
  selector: store => {
    return store.state.pipe(
      map(state => state.r)
    );
  }
})
```

These are the only changes I did to `decorators.ts`

- `ConnectToSettings` will have generics of `<T, R = T | any>`
- selector will now return an observable with generic of `R`
- `getSource` function requires a return type for the `source.subscribe` to detect what it should return

```ts
export interface ConnectToSettings<T, R = T | any> {
  onChanged?: string;
  selector: ((store: Store<T>) => Observable<R>);
  setup?: string;
  target?: string;
  teardown?: string;
}

export function connectTo<T, R = any>(settings?: ((store: Store<T>) => Observable<R>) | ConnectToSettings<T, R>) {
  const store = Container.instance.get(Store) as Store<T>;

  function getSource(): Observable<any> {
    if (typeof settings === "function") {
      const selector = settings(store);
```

Pull request opened https://github.com/zewa666/aurelia-store/pull/30

**Comment by zewa666** [comment]
Thanks, merged and released

**Comment by Belpois** [comment]
@zewa666 I just noticed that the NPM package that was release (0.23.2) doesn't have the necessary changes in the declaration files. Although the src is fine.

**Comment by zewa666** [comment]
yes true, I'm sorry I didn't properly add the built files :(
new release is out
